### ISSUE TITLE
Add Unity Ads (mraid) support

### ISSUE THREAD

**Issue by aglitchman** [indiesoftby/defold-playable-ads#14]

**Comment by aglitchman** [comment]
https://forum.defold.com/t/defold-for-playable-ads/68689/42?u=aglitchman

**Comment by gabahulk** [comment]
Awesome! This made me want to learn Defold!

**Comment by aglitchman** [comment]
Okay, generally speaking, I got it to pass Unity ad tester test. 

![Screenshot_20240127_032234_Ad Testing](https://github.com/indiesoftby/defold-playable-ads/assets/193258/409a94c8-5805-4805-9b40-60aaef40ff8d)

Next step is to improve the included example to test how audio works.

**Comment by aglitchman** [comment]
Completed in #17
